### ISSUE TITLE
Keycloak 22 incompatible

### ISSUE THREAD

**Issue by belfhi** [evosec/keycloak-ipaddress-authenticator#1]
the migration from `javax` to `jakarta` in Keycloak 22 breaks this Authenticator.
I successfully built my own version by building against the Keycloak 22 libraries,
no other changes in the code were needed.

**Comment by Nikos410** [comment]
Hey Johannes, thanks for the heads-up! I bumped the keycloak version and published a new release :)

https://github.com/evosec/keycloak-ipaddress-authenticator/releases/tag/22.0.3_1
