### ISSUE TITLE
Missing form fields?

### ISSUE THREAD

**Issue by ksheumaker** [evosec/keycloak-ipaddress-authenticator#2]
Trying to test this on keycloak 23.0.3 and when I go to configure the flow, the form doesn't allow me to enter fields for the IP address.  See attached screenshot.  Tried in chrome and firefox just to make sure it wasn't a browser issue.

![Screenshot 2024-01-03 at 10 25 41 AM](https://github.com/evosec/keycloak-ipaddress-authenticator/assets/12651/ff539ad8-374a-4cd8-903c-75d0fc400735)

**Comment by Nikos410** [comment]
Hey @ksheumaker, thanks for the report!

This is interesting! When adding a new condition of this type I can confirm that the input is indeed missing. But when I go and edit our existing configuration (which we added when we were running Keycloak 22) everything works fine:

![image](https://github.com/evosec/keycloak-ipaddress-authenticator/assets/20876882/95fd2298-a894-4ce5-ac6c-5d50fba5c622)

I know that the `MULTIVALUED_STRING_TYPE` has been broken before, maybe this is a regression.

**Comment by Nikos410** [comment]
Hey @ksheumaker it seems that a default value is now required for multi value inputs. Can you please try the attached version of the authenticator and verify that it works?
[keycloak-ipaddress-authenticator-23.0.3_2-jar-with-dependencies.tar.gz](https://github.com/evosec/keycloak-ipaddress-authenticator/files/13937347/keycloak-ipaddress-authenticator-23.0.3_2-jar-with-dependencies.tar.gz)

**Comment by Nikos410** [comment]
No need to apologize! Thank you for testing, merging #3 and creating a new release now :)
