### ISSUE TITLE
Is this plugin could be used for registration only?

### ISSUE THREAD

**Issue by ttimot24** [evosec/keycloak-ipaddress-authenticator#4]
I have a use case where I have to blacklist all countries except one for registration, but for authentication everything is whitelisted

**Comment by Nikos410** [comment]
Hey Timot, you can use the authenticator in any flow you like. In your case, you would add the ip-address authenticator to the Registration Flow, but keep the Browser flow as it is:

![image](https://github.com/user-attachments/assets/5ee7d191-db36-4ea8-9304-4aaba88d0b70)

However, this authenticator does not do GeoIP on it's own. So you have to add all IP ranges, that you want to whitelist, yourself.

**Comment by ttimot24** [comment]
Perfect, thank you!
