### ISSUE TITLE
Add a LICENSE File for Clarification on Commercial Use

### ISSUE THREAD

**Issue by Florzl** [evosec/keycloak-ipaddress-authenticator#8]
Hi,

Thank you for creating this plugin; it’s a fantastic tool! I wanted to inquire if it’s possible to use this plugin for commercial purposes.

Currently, I noticed that the repository does not have a LICENSE file, so the usage terms are unclear. Could you kindly add a LICENSE file with your preferred licensing terms to clarify the permitted use cases? This would be greatly helpful for understanding how the project can be used.

Looking forward to your response!

**Comment by Nikos410** [comment]
Servus @Florzl,

feel free to use this plugin for commercial purposes.

I've added the MIT license to clarify that commercial use is fine :)

Best
Nikos
